language: rust

env:
  global:
    - PROJECT_NAME=vndb

matrix:
  include:
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin
      cache: cargo
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
      cache: cargo

sudo: false

script:
  - cargo test --features tokio-on,rustls
